mohammadmirza99/watch_bnb

app/models/request.rb, app/models/review.rb, app/models/user.rb, app/models/watch.rb, db/migrate/20200225151029_add_column_to_watches.rb, db/schema.rb, db/seeds.rb
- add validation to each model
- add image_url to watches table;
=> Model validation

app/models/request.rb, app/models/review.rb, app/models/user.rb, app/models/watch.rb, db/migrate/20200225151029_add_column_to_watches.rb, db/schema.rb, db/seeds.rb
Created 3  users.
Created 3 watches, linked to users via User_id.
Created 3 requests, linked to users and watches via user_id and watch_id.
Created 3 reviews, linked to user and watches via user_id and watch_id.
=> Seed generation.

app/controllers/users_controller.rb, db/seeds.rb
Updated the seeds file to fill with appropriate seeds.
=> Modified seeds folder

app/controllers/requests_controller.rb, app/controllers/watches_controller.rb, app/views/requests/_form.html.erb, app/views/requests/new.html.erb, app/views/watches/_form.html.erb, app/views/watches/edit.html.erb
=> Simple form

app/controllers/requests_controller.rb, app/views/requests/_form.html.erb, app/views/requests/new.html.erb, app/views/watches/_form.html.erb, app/views/watches/index.html.erb, app/views/watches/show.html.erb
-Fixed create new+create for "requests"
=> Fixed simple form to create request

app/controllers/watches_controller.rb, app/views/watches/_form.html.erb, app/views/watches/new.html.erb
- Fixed new/create methods in the Watch controller.
- Fixed simple form + redirects to the correct page
=> Implemented create watch

app/models/review.rb, db/seeds.rb
- Fixed seeds so that the reviews, watches and requests are linked to Users and Watches on any device (no longer fixed ID dependent)
- Fixed an issue in the review models for inclusion, turned into an array.
=> Fixed seeds, fixed inclusion in review models

app/controllers/pages_controller.rb, app/views/pages/home.html.erb, db/seeds.rb
-Added cards to the home page.
=> Added cards to the home page showing all the watches in seed

app/views/pages/home.html.erb, app/views/users/show.html.erb
- Made changes to requests path
=> Fixed requests

app/controllers/watches_controller.rb, app/models/watch.rb, app/views/watches/index.html.erb
- Created edit update and delete method in Watches Controller.
- Added Edit and Delete links to each watch card in the watches/index page.
=> Added Update and Edit options for watches

app/assets/stylesheets/components/_card_dash.scss, app/assets/stylesheets/components/_dashboard-container.scss, app/assets/stylesheets/components/_index.scss, app/views/users/show.html.erb, app/views/watches/show.html.erb
- Create a card in the dashboard
=> dash card ready for the first demo

app/assets/stylesheets/components/_dashboard-container.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_request-card.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/requests/index.html.erb, app/views/shared/_sidebar.html.erb, app/views/users/show.html.erb, app/views/watches/index.html.erb, app/views/watches/new.html.erb
=> dashboard is completed

app/controllers/application_controller.rb, app/controllers/requests_controller.rb, app/models/watch.rb, app/views/pages/home.html.erb, db/seeds.rb
- Fixed redirect when booking.
- Fixed Navbar button sign in redirect.
=> Fix Book redirect and Navbar Sign In

app/assets/stylesheets/components/_request-card.scss, app/views/pages/home.html.erb, app/views/requests/index.html.erb, app/views/shared/_card_dash.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_request-card.html.erb, app/views/users/show.html.erb
request card is updated, navbar modified
=> request card is updated, navbar modified

app/views/pages/home.html.erb
=> Made a change to the view page

app/assets/stylesheets/components/_homepage-container.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/watches_controller.rb, app/models/watch.rb, app/views/pages/home.html.erb, db/migrate/20200226210809_remove_img_column.rb, db/schema.rb
=> style added

app/assets/stylesheets/components/_homepage-container.scss, app/views/pages/home.html.erb
=> bug fix home page

app/views/pages/home.html.erb, db/seeds.rb
=> Added seeds

app/javascript/components/modal.js, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/requests/_form.html.erb, app/views/requests/new.html.erb, app/views/watches/index.html.erb, package-lock.json, package.json, yarn.lock
- Added date picker functionality when reserving a watch.
- Testing modal functionality on home page, waiting for the card design to finish before updating.
=> testing modal functionality, added datepicker to book a watch

app/assets/stylesheets/components/_user_watch_card.scss, app/views/pages/home.html.erb, app/views/shared/_card-user.html.erb, app/views/watches/index.html.erb, db/schema.rb
- Watch cards for the home page
=> User watch card

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_user_watch_card.scss, app/javascript/components/modal.js, app/views/pages/home.html.erb, app/views/watches/index.html.erb
- Designed modal
- Removed border radius
=> Modal and calendar

app/assets/stylesheets/components/_card_dash.scss, app/assets/stylesheets/components/_edit-form.scss, app/assets/stylesheets/components/_index.scss, app/views/requests/index.html.erb, app/views/shared/_card_dash.html.erb, app/views/watches/edit.html.erb, app/views/watches/index.html.erb
- request card
- edit form for watches
=> Finish request

app/assets/stylesheets/components/_edit-form.scss, app/assets/stylesheets/components/_form_input_image.scss, app/assets/stylesheets/components/_index.scss, app/views/watches/new.html.erb
- change the background of the edit form
- create a form for new_watch
=> Watch new form

app/assets/stylesheets/components/_edit-form.scss, app/views/pages/home.html.erb, app/views/requests/_form.html.erb, app/views/requests/new.html.erb
=> resquests form updated

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer-container.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, app/views/watches/show.html.erb
=> homepage font redesigned
